name: all-checks-passed
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        unlabeled,
        labeled,
        milestoned,
      ]

jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@db5bb1339be1d4b3d9c8a3b8ba6c1906bdd55c2a
        with:
          delay: '3'
          retries: '30'
          polling_interval: '1'
          checks_exclude: 'golangci-lint'
